### ISSUE TITLE
[Bug] Breaks other plugins as of 1.2.0

### ISSUE THREAD

**Issue by xamionex** [taffyko/LCNiceChat#2]
As of NiceChat 1.2.0 it breaks MoreCompany's cosmetics, and gives a bunch of other exceptions for the hud
[1.1.0.log](https://github.com/taffyko/LCNiceChat/files/13691714/1.1.0.log): Everything works as expected
[1.2.0.log](https://github.com/taffyko/LCNiceChat/files/13691716/1.2.0.log): MC doesn't load cosmetics, and exceptions for other mods, I'm pretty sure L682 and L1261 is at fault

Reason for the two logs is so that you can differentiate if something is an issue with your mod
[Here's a diff checker page with them compared](https://www.diffchecker.com/8GB3rby1/)

This is my r2modman code: 018c718d-fbdd-aa01-3d71-a3f794de449a

Let me know if you want me to test something for you/see if changing/disabling something fixes it

**Comment by xamionex** [comment]
Still an issue in 1.2.1 unfortunately
You should test with 3rdperson mod because it shows the cosmetics if you enable them in the settings:
NiceChat Disabled:
![image](https://github.com/taffyko/LCNiceChat/assets/57235791/0c610239-b601-4dc0-a927-a5544621ad56)
NiceChat 1.2.1:
![image](https://github.com/taffyko/LCNiceChat/assets/57235791/f76ce1f9-24bb-41cd-9cde-cb2ff90666af)

**Comment by xamionex** [comment]
Mod profile for testing if needed: 018c7bc8-263d-9c10-d23e-782199705ded
Mod List:
```
NiceChat by taffyko
inacraft_cosmetics_megapack by broiiler
MoreCompany by notnotnotswipez
BepInExPack by BepInEx
3rdPerson by Verity
```
Enable MoreCompany cosmetics support in verity.3rdperson.cfg and you can see cosmetics when it works

**Comment by taffyko** [comment]
thank you for all the details and reproduction steps! — i'm working on a fix!

**Comment by taffyko** [comment]
alright, 1.2.2 released, things should be fixed now
— thanks again for the high-quality report, feel free to open a new ticket if you have any more issues!
