### ISSUE TITLE
Only host able to utilize Nice Chat

### ISSUE THREAD

**Issue by VioletXe** [taffyko/LCNiceChat#5]
I don't know why, but for some reason only the host isn't restricted by the vanilla character limit. It was working fine once, but something updates somewhere and I don't know why it's not working anymore. This is the profile I'm working with.

018d97dc-f909-f061-dda8-d0aa5ac301bf

**Comment by taffyko** [comment]
i've published a fix for this in v1.2.5 — let me know if you run into any more issues!
